### ISSUE TITLE
Update documentation - error in documentation

### ISSUE THREAD

**Issue by jokamax** [paypal/Checkout-PHP-SDK#12]
1. Set up transaction 
[https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/#on-the-server](https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/#on-the-server)

```
createOrder: function() {
  return fetch('/my-server/create-paypal-transaction')
    .then(function(res) {
      return res.json();
    }).then(function(data) {
      return data.orderID;
    });
}
```
 return data.orderID; ====> return data.result.id;

2. Capture transaction
[https://developer.paypal.com/docs/checkout/reference/server-integration/capture-transaction/](https://developer.paypal.com/docs/checkout/reference/server-integration/capture-transaction/)

```
onApprove: function(data) {
  return fetch('/my-server/capture-paypal-transaction', {
    body: JSON.stringify({
      orderID: data.orderID
    })
  }).then(function(res) {
    return res.json();
  }).then(function(details) {
    alert('Transaction funds captured from ' + details.payer_given_name);
}
```
Error 1 : **Request with GET/HEAD method cannot have body**
Error 2 : details.payer_given_name doesn't exist

My solution (not better than another) : 
```
onApprove: function(data) {
    return fetch(/my-server/capture-paypal-transaction?orderID=' + data.orderID)
    .then(function(res) {
      return res.json();
    }).then(function(details) {
      alert('Transaction funds captured from ' + details.result.payer.name.given_name);
    });
  }
```

Thanks

**Comment by rajarampadmanathan** [comment]
HI @jokamax ,
Regarding error 1:
Looks like `/my-server/capture-paypal-transaction` endpoint which you implemented at server side is an GET one. Samples are provided considering capture endpoint as an POST (To align with the REST service practices).

Regarding error 2:
Since `/my-server/capture-paypal-transaction` is an endpoint which you implemented at server side,
`details` object in the response is depends on which is being returned by above endpoint. The provided sample assumes API returns something s like below in `/my-server/capture-paypal-transaction`.
```
{
"payer_given_name": "sample name"
}

``` 
Whereas in you sample, whole PayPal API/SDK response is returned in the details.result.
```
{
"result": <<PAYPAL CAPTURE API RESPONSE>>
}
```

**Comment by jokamax** [comment]
@rajarampadmanathan 
In the sample : 
return fetch('/my-server/capture-paypal-transaction', {
    body: JSON.stringify({
      orderID: data.orderID
    })
  })
As writen : this is a GET.
By default fetch uses the GET method.
And as no $_POST in the server sample I misunderstood...

**Comment by ganeshramc** [comment]
Hi @jokamax, we'll try to make it clearer. Thanks for the clarification! If you have any other questions, we'll keep this issue open for 7 days. We'll be closing the issue after that. Thanks 😄
