### ISSUE TITLE
Issues in CreateOrder class

### ISSUE THREAD

**Issue by boldness1** [paypal/Checkout-PHP-SDK#85]
1. In CreateOrder class,

return $response does not trigger the client side to keep redirecting the user to the payment form,I had to enable;

`echo json_encode($response->result, JSON_PRETTY_PRINT);` 

2.by default `$response->result->id` considered as orderID but should be changed as `$response->result->orderID` for client side to be able to recognise the order ID for smart button side.

Also the debug section when enabled(set true) the default debug output is not proper when printing the debug info, so it returns the paypal modal with js console error.

**Comment by targor** [comment]
already mentioned the json response in : https://github.com/paypal/Checkout-PHP-SDK/issues/82 
:)

**Comment by tiffanyrzhou** [comment]
@boldness1  @targor  Thanks for reaching out and providing feedback. 
1) The samples written for the sdk aren't specific to the smart payment button client side, rather they are geared towards a more generic client side. We have noted down the the integration friction points between these two products, and will work on our documentation to clarify these issues. Please take a look at the [RunAll.php](https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/CaptureIntentExamples/RunAll.php) on how we handle the response from create order. Like you suggested the create order returns the full http response, including header information, and the smart payment buttons integration is looking for the body of the response. 

2) The result is from our API response in which the order ID attribute is called "id". Since in this context, we only have one id our API is defined to call it "id". You can change this on your side when passing to smart button sides this is specific to smart button integration. 

3) For default debug output issue. Please open an issue over at the smart payment buttons repo https://github.com/paypal/paypal-checkout-components/issues/new/choose 

Again, thanks for the feedback, we will work with the smart payment buttons team and update the docs.
